language: python
before_install:
  - pip install pycodestyle
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
  - pytest --cov=artellapipe
  - sphinx-apidoc -f -e -o docs/sphinx artellapipe
  - sphinx-build -M html ./docs/sphinx ./
after_success:
  - coveralls
  - cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: TM2karhBUPEvMknOYb7sV3H6BJ2ZQxnPiUVm20DrhNsNibhRJhU2rvRWqgP+/rY29JgBFF/rLrH5AkG6RR8hbpGLyLzkKoYu3jEv+qOwv56LNWzZjQZkpC+MVj97kkXT3XrFmM5mm4zmTcdWBvrCCLyzo0pfF5Gs07GOjDpOwLKzo/GOCQK5EyY+2pt6znx8HkIJGDLQnXJPt67iBd4IrcHzWFHm0mZSvqNI4ghEUhkwXEmyofL7MwEYdF337dDvGSC+C8qho32SIHpVyw6tbzay0JYhz0zCUQngGVBlc6VdYp3NqYYkUH5DBQUuo0TKaJ8V2/OHLAudJ1NFuWOwlN/Dk6Rzdkkw4Gep9hCPoXJfvMZsLkcAHzOpqvfRptbck5sTsZKpVZ6umPzMBaOv7Qsb2rdRcWsHZK0D1jI0HUXnxXjN6sg1DUvOLS7cteZxtSs8/8pymw4czd2jCJxTnbGegsdYsSGHoj1BpM9xXq9FCxEc1XhdmrV7wl+cQQVUYt8wQnoNxSpdLiJKmYHozBOxqxG7dDKMYkBt7pmEupf3kyrrUyiTTq3xB707Ja8KPgRP/SnBt0HsWIOYAOWxftUzMeJp96ShiAdWwRmDW9bOblY0vltoKBhN5d6ddoucWimaQuJEvIxdP/mu1bujpd6vxyKtNOV6Q24r5VT2Mps=
    on:
      branch: master
      tags: true